theme: jekyll-theme-cayman
nav:
  - title: "Home"
    url: "/"
  - title: "Design Contests"
    url: "/design-contests"
  - title: "Undergraduate Level"
    url: "/undergraduate-level"
  - title: "Masters Level"
    url: "/masters-level"
  - title: "PhD Level"
    url: "/phd-level"
  - title: "License"
    url: "/license"